//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBarFootball.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortName { get; set; }
        public string PictureUrl { get; set; }
        public string VideoUrl { get; set; }
        public int Cost { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int CardRarity { get; set; }
        public int CardType { get; set; }
        public int CardStyle { get; set; }
        public Nullable<int> CardPosition { get; set; }
        public Nullable<int> CardClub { get; set; }
        public Nullable<int> CardNation { get; set; }
        public Nullable<int> CardLeague { get; set; }
    
        public virtual CardClub CardClub1 { get; set; }
        public virtual CardLeague CardLeague1 { get; set; }
        public virtual CardNation CardNation1 { get; set; }
        public virtual CardPosition CardPosition1 { get; set; }
        public virtual CardRarity CardRarity1 { get; set; }
        public virtual CardStyle CardStyle1 { get; set; }
        public virtual CardType CardType1 { get; set; }
    }
}
