//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBarFootball.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardLeague
    {
        public CardLeague()
        {
            this.Card = new HashSet<Card>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Card> Card { get; set; }
    }
}
