//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBarFootball.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoobarfootballEntities : DbContext
    {
        public FoobarfootballEntities()
            : base("name=FoobarfootballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Card> Card { get; set; }
        public DbSet<CardClub> CardClub { get; set; }
        public DbSet<CardLeague> CardLeague { get; set; }
        public DbSet<CardNation> CardNation { get; set; }
        public DbSet<CardPosition> CardPosition { get; set; }
        public DbSet<CardRarity> CardRarity { get; set; }
        public DbSet<CardStyle> CardStyle { get; set; }
        public DbSet<CardType> CardType { get; set; }
    }
}
